### ISSUE TITLE
marc_to_folio.conditions returning empty locations array

### ISSUE THREAD

**Issue by AndrewIsh** [FOLIO-FSE/MARC21-To-FOLIO#31]
I'm getting up to speed on data migration, so apologies if this issue is erroneous. I'm using `develop`.

Running a holdings file creation is failing due to an empty locations array being returned from `marc_to_folio/conditions.py`. The failure looks like this:

```
andrew@kessel:~/folio/MARC21-To-FOLIO$ PYTHONPATH="${PYTHONPATH}:../FolioClient" pipenv run python3.9 main_holdings.py ../test-migration/marc ../test-migration/out http://localhost:9130 diku diku_admin admin voyager -m ../test-migration/mapping_files
loaded 1 migrated instance IDs
Locations in map: 2
True
Dedaule location code KU/CC/DI/P
2 Instance ids in map
Fetching locations
Fetched 8 locations
Fetched 5 electronic_access_relationships
Default contributor name type is 2e48e713-17f3-4c13-a9f8-23845bb210aa
3 contrib_name_types in tenant
Current user id is 4f583717-2330-57a5-8d44-5ae482cbffab
Fetched 5 holdings types
Traceback (most recent call last):
  File "/home/andrew/folio/MARC21-To-FOLIO/main_holdings.py", line 113, in <module>
    main()
  File "/home/andrew/folio/MARC21-To-FOLIO/main_holdings.py", line 92, in main
    mapper = RulesMapperHoldings(
  File "/home/andrew/folio/MARC21-To-FOLIO/marc_to_folio/rules_mapper_holdings.py", line 24, in __init__
    self.default_location_id = self.get_ref_data_tuple(
TypeError: 'NoneType' object is not subscriptable
```

Looking at `conditions.py` I think the issue is that https://github.com/FOLIO-FSE/MARC21-To-FOLIO/blob/develop/marc_to_folio/conditions.py#L17-L22 is populating the array, but then it is emptied at https://github.com/FOLIO-FSE/MARC21-To-FOLIO/blob/develop/marc_to_folio/conditions.py#L49. I notice there is also another population in `condition_set_location_id_by_code` but, as far as I can see, this is never called.

As I say, I'm still getting to grips with data migration, so apologies if I am misunderstanding.

**Comment by AndrewIsh** [comment]
OK, I'm going to tentatively close this on the basis that it is erroneous. I now understand that `condition_set_location_id_by_code` is invoked based on the condition type definition in `mfhd_rules.json`. So, I'm guessing the emptying of the array described in the original post isn't an issue because it is later populated as the rules are processed. Also, I'm now on `honeysuckle` and notice this doesn't contain the array emptying.
